redis_ambassador:
  image: svendowideit/ambassador
  container_name: redis_ambassador
  expose:
   - "6379"
  environment: 
    - REDIS_PORT_6379_TCP=tcp://192.168.1.52:6379

redis_client: 
  image: anapsix/webdis
  container_name: redis_client
  links: 
    - redis_ambassador:redis
  ports:
   - 7379:7379
